### ISSUE TITLE
Вставить вместо "Купить"?

### ISSUE THREAD

**Issue by realbsb** [stickpro/opencart-recall#1]
Привет! А можно каким-то образом погасить вывод корзины и заменить кнопку "Купить" вашим модулем в ocStore 3.0.3?

**Comment by stickpro** [comment]
Привет, вы можете взять за основу мой модуль, вам достаточно на кнопку купить повесить новое событие для отправки сообщения, а не использовать ваше для переносам товара в корзину пример кода для вызова события находится в шаблоне https://github.com/stickpro/opencart-recall/blob/main/upload/catalog/view/theme/default/template/extension/module/recall_tg.twig#L20

**Comment by realbsb** [comment]
Спасибо!
